### ISSUE TITLE
Background highlight for line-based explanations

### ISSUE THREAD

**Issue by ichoosetoaccept** [ExplainDev/feedback#2]
Hiyo, me again

I noticed that the browser extension displays an "Explain" button on the far right in a code block on pages such as Gitlab (in this example). It's hard to tell which line is meant by the "Explain" button because it's too far off to the right with respect to the code (all the way to the left) it's trying to explain. Here's a GIF to demonstrate:
![CleanShot 2022-09-28 at 23 11 54](https://user-images.githubusercontent.com/1242091/192890278-8f3a4784-b48b-4c54-b10e-440228d84519.gif)

An easy fix for this would be to give the full DIV you're using to place the "Explain" button (for the current line of code) some 
color background to select the entire line.

Cheers!

**Comment by iphutch** [comment]
Thanks @ichoosetoaccept . The Explain button pictured here that appears on hover will explain the entire code-block and isn't tied to a line.
For single line or smaller section explanations, you can select the lines you want explained and click the explain selection button that pops up closer to the code.

**Comment by ichoosetoaccept** [comment]
How about about when you hover over the explain button, you have a translucent box appear in whatever color you like, over what is about to be explained? Could be a line.. could be a block, the whole code block...

This way, from a user's perspective, you'd know exactly what is about to be explained 😀
