### ISSUE TITLE
No response to first query after exiting and re-entering VS Code

### ISSUE THREAD

**Issue by iphutch** [ExplainDev/feedback#3]
Settings: Spanish and Advanced.
"Es algo raro pero siempre que salgo de VS Code y entro nuevamente para hacer una explicación no me da la explicación pero luego de salir de el archivo de explicación y poner lo que quiero explicar nuevamente funciona."
"Solamente queda sin nada la explicación pero ya si lo hago otra vez funciona bien"

![image](https://user-images.githubusercontent.com/21109162/193076120-833da5af-47b9-4395-8ae5-38f30513e067.png)
![image](https://user-images.githubusercontent.com/21109162/193076167-79285c04-bbeb-4ebb-8dc3-4df263135ae7.png)

**Comment by ediardo** [comment]
Fixed.
